/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import practica.pkg5.crypto.Archivo;
import practica.pkg5.crypto.CryptoHibrida;
import practica.pkg5.crypto.RSA;

/**
 *
 * @author user1
 */
public class Ventana extends javax.swing.JFrame {

    String rutaArchivo;
    String rutaLlavePrivada, rutaLlavePublica;
    private PrivateKey llavePrivada;
    private PublicKey llavePublica;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCifrarPublica = new javax.swing.JButton();
        lblCifrarRutaPublica = new javax.swing.JLabel();
        btnCifrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDescifrarLlavePrivada = new javax.swing.JButton();
        lblDescifrarRutaLlavePrivada = new javax.swing.JLabel();
        btnDescifrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnFirmarLlavePrivada = new javax.swing.JButton();
        lblFirmarRutaLlavePrivada = new javax.swing.JLabel();
        btnFirmar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnVerificarPublica = new javax.swing.JButton();
        lblVerificarRutaPublica = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCifrarYFirmarPublica = new javax.swing.JButton();
        lblCifrarYFirmarRutaPublica = new javax.swing.JLabel();
        btnCifrarYFirmar = new javax.swing.JButton();
        btnCifrarYFirmarLlavePrivada = new javax.swing.JButton();
        lblCifrarYFirmarRutaLlavePrivada = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnDescifrarYVerificarPublica = new javax.swing.JButton();
        lblDescifrarYVerificarRutaPublica = new javax.swing.JLabel();
        btnDescifrarYVerificarLlavePrivada = new javax.swing.JButton();
        lblDescifrarYVerificarRutaLlavePrivada = new javax.swing.JLabel();
        btnDescifrarYVerificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnGenerarParDeLlaves = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        lblRutaArchivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCifrarPublica.setText("Llave pública...");
        btnCifrarPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarPublicaActionPerformed(evt);
            }
        });

        lblCifrarRutaPublica.setText("Ningún archivo seleciconado...");

        btnCifrar.setText("CONTINUAR");
        btnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCifrarPublica)
                .addGap(18, 18, 18)
                .addComponent(lblCifrarRutaPublica, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCifrarPublica)
                    .addComponent(lblCifrarRutaPublica))
                .addGap(18, 18, 18)
                .addComponent(btnCifrar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cifrar", jPanel1);

        btnDescifrarLlavePrivada.setText("Llave privada...");
        btnDescifrarLlavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarLlavePrivadaActionPerformed(evt);
            }
        });

        lblDescifrarRutaLlavePrivada.setText("Ningún archivo seleciconado...");

        btnDescifrar.setText("CONTINUAR");
        btnDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDescifrarLlavePrivada)
                .addGap(18, 18, 18)
                .addComponent(lblDescifrarRutaLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescifrarLlavePrivada)
                    .addComponent(lblDescifrarRutaLlavePrivada))
                .addGap(18, 18, 18)
                .addComponent(btnDescifrar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Descifrar", jPanel2);

        btnFirmarLlavePrivada.setText("Llave privada...");
        btnFirmarLlavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarLlavePrivadaActionPerformed(evt);
            }
        });

        lblFirmarRutaLlavePrivada.setText("Ningún archivo seleciconado...");

        btnFirmar.setText("CONTINUAR");
        btnFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnFirmarLlavePrivada)
                .addGap(18, 18, 18)
                .addComponent(lblFirmarRutaLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirmarLlavePrivada)
                    .addComponent(lblFirmarRutaLlavePrivada))
                .addGap(18, 18, 18)
                .addComponent(btnFirmar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Firmar", jPanel3);

        btnVerificarPublica.setText("Llave pública...");
        btnVerificarPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPublicaActionPerformed(evt);
            }
        });

        lblVerificarRutaPublica.setText("Ningún archivo seleciconado...");

        btnVerificar.setText("CONTINUAR");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnVerificarPublica)
                .addGap(18, 18, 18)
                .addComponent(lblVerificarRutaPublica, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificarPublica)
                    .addComponent(lblVerificarRutaPublica))
                .addGap(18, 18, 18)
                .addComponent(btnVerificar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Verificar", jPanel4);

        btnCifrarYFirmarPublica.setText("Llave pública...");
        btnCifrarYFirmarPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarYFirmarPublicaActionPerformed(evt);
            }
        });

        lblCifrarYFirmarRutaPublica.setText("Ningún archivo seleciconado...");

        btnCifrarYFirmar.setText("CONTINUAR");
        btnCifrarYFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarYFirmarActionPerformed(evt);
            }
        });

        btnCifrarYFirmarLlavePrivada.setText("Llave privada...");
        btnCifrarYFirmarLlavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarYFirmarLlavePrivadaActionPerformed(evt);
            }
        });

        lblCifrarYFirmarRutaLlavePrivada.setText("Ningún archivo seleciconado...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnCifrarYFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCifrarYFirmarPublica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCifrarYFirmarLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCifrarYFirmarRutaLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCifrarYFirmarRutaPublica, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCifrarYFirmarPublica)
                    .addComponent(lblCifrarYFirmarRutaPublica))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCifrarYFirmarLlavePrivada)
                    .addComponent(lblCifrarYFirmarRutaLlavePrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnCifrarYFirmar)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Cifrar y firmar", jPanel5);

        btnDescifrarYVerificarPublica.setText("Llave pública...");
        btnDescifrarYVerificarPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarYVerificarPublicaActionPerformed(evt);
            }
        });

        lblDescifrarYVerificarRutaPublica.setText("Ningún archivo seleciconado...");

        btnDescifrarYVerificarLlavePrivada.setText("Llave privada...");
        btnDescifrarYVerificarLlavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarYVerificarLlavePrivadaActionPerformed(evt);
            }
        });

        lblDescifrarYVerificarRutaLlavePrivada.setText("Ningún archivo seleciconado...");

        btnDescifrarYVerificar.setText("CONTINUAR");
        btnDescifrarYVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarYVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnDescifrarYVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDescifrarYVerificarPublica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDescifrarYVerificarLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDescifrarYVerificarRutaLlavePrivada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDescifrarYVerificarRutaPublica, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescifrarYVerificarPublica)
                    .addComponent(lblDescifrarYVerificarRutaPublica))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescifrarYVerificarLlavePrivada)
                    .addComponent(lblDescifrarYVerificarRutaLlavePrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnDescifrarYVerificar)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Descifrar y verificar", jPanel6);

        btnGenerarParDeLlaves.setText("GENERAR PAR DE LLAVES");
        btnGenerarParDeLlaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarParDeLlavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(btnGenerarParDeLlaves, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(btnGenerarParDeLlaves, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Generar llaves", jPanel7);

        btnArchivo.setText("Archivo...");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        lblRutaArchivo.setText("Ningún archivo seleciconado...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRutaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArchivo)
                    .addComponent(lblRutaArchivo))
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            byte[] out = ch.cifrar(archivo.getInfo(), llavePublica);
            archivo.saveBytes("Cifrado.txt", out);
            JOptionPane.showMessageDialog(null, "Archivo cifrado exitosamente");
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_btnCifrarActionPerformed

    private void btnCifrarPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarPublicaActionPerformed
        abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblCifrarRutaPublica.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnCifrarPublicaActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 2);
        if (rutaArchivo != null) {
            lblRutaArchivo.setText(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnDescifrarLlavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarLlavePrivadaActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblDescifrarRutaLlavePrivada.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnDescifrarLlavePrivadaActionPerformed

    private void btnDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            String resultado = ch.descifrar(archivo.getBytes(), llavePrivada);
            archivo.saveInfo("Descifrado.txt", resultado);
            JOptionPane.showMessageDialog(null, "Archivo descifrado exitosamente");
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_btnDescifrarActionPerformed

    private void btnFirmarLlavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarLlavePrivadaActionPerformed
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblFirmarRutaLlavePrivada.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnFirmarLlavePrivadaActionPerformed

    private void btnFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);

        byte[] firmar = ch.firmar(archivo.getInfo(), llavePrivada);
        archivo.saveBytes("Firmado.txt", firmar);
        JOptionPane.showMessageDialog(null, "Archivo firmado exitosamente");
    }//GEN-LAST:event_btnFirmarActionPerformed

    private void btnVerificarPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPublicaActionPerformed
        // TODO add your handling code here:
         abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblVerificarRutaPublica.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnVerificarPublicaActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            if (ch.verificar(archivo.getBytes(), llavePublica)) {
                JOptionPane.showMessageDialog(null, "La firma es correcta");
            } else {
                JOptionPane.showMessageDialog(null, "La firma es incorrecta");
            }
        } catch (UnsupportedEncodingException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnCifrarYFirmarPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarYFirmarPublicaActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblCifrarYFirmarRutaPublica.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnCifrarYFirmarPublicaActionPerformed

    private void btnCifrarYFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarYFirmarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            byte[] cifrarYFirmar = ch.cifrarYFirmar(archivo.getInfo(), llavePrivada, llavePublica);
            archivo.saveBytes("CifradoFirmado.txt", cifrarYFirmar);
            JOptionPane.showMessageDialog(null, "Archivo cifrado y firmado exitosamente");
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
        }
    }//GEN-LAST:event_btnCifrarYFirmarActionPerformed

    private void btnCifrarYFirmarLlavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarYFirmarLlavePrivadaActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblCifrarYFirmarRutaLlavePrivada.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnCifrarYFirmarLlavePrivadaActionPerformed

    private void btnDescifrarYVerificarPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarYVerificarPublicaActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblDescifrarYVerificarRutaPublica.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnDescifrarYVerificarPublicaActionPerformed

    private void btnDescifrarYVerificarLlavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarYVerificarLlavePrivadaActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblDescifrarYVerificarRutaLlavePrivada.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnDescifrarYVerificarLlavePrivadaActionPerformed

    private void btnDescifrarYVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarYVerificarActionPerformed
        // TODO add your handling code here:
        CryptoHibrida ch = new CryptoHibrida();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            String descifrarYverificar = ch.descifrarYverificar(archivo.getBytes(), llavePrivada, llavePublica);
            archivo.saveInfo("DescifradoYVerificado", descifrarYverificar);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error");
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDescifrarYVerificarActionPerformed

    private void btnGenerarParDeLlavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarParDeLlavesActionPerformed
        RSA rsa = new RSA();
        rsa.generarLLaves();
        JOptionPane.showMessageDialog(null, "Llaves generadas exitosamente");
    }//GEN-LAST:event_btnGenerarParDeLlavesActionPerformed

    private void abrirArchivo(int opcion) {
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File abre = file.getSelectedFile();
        switch (opcion) {
            case 0:
                rutaLlavePrivada = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 1:
                rutaLlavePublica = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 2:
                rutaArchivo = abre != null ? abre.getAbsolutePath() : null;
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnCifrarPublica;
    private javax.swing.JButton btnCifrarYFirmar;
    private javax.swing.JButton btnCifrarYFirmarLlavePrivada;
    private javax.swing.JButton btnCifrarYFirmarPublica;
    private javax.swing.JButton btnDescifrar;
    private javax.swing.JButton btnDescifrarLlavePrivada;
    private javax.swing.JButton btnDescifrarYVerificar;
    private javax.swing.JButton btnDescifrarYVerificarLlavePrivada;
    private javax.swing.JButton btnDescifrarYVerificarPublica;
    private javax.swing.JButton btnFirmar;
    private javax.swing.JButton btnFirmarLlavePrivada;
    private javax.swing.JButton btnGenerarParDeLlaves;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVerificarPublica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCifrarRutaPublica;
    private javax.swing.JLabel lblCifrarYFirmarRutaLlavePrivada;
    private javax.swing.JLabel lblCifrarYFirmarRutaPublica;
    private javax.swing.JLabel lblDescifrarRutaLlavePrivada;
    private javax.swing.JLabel lblDescifrarYVerificarRutaLlavePrivada;
    private javax.swing.JLabel lblDescifrarYVerificarRutaPublica;
    private javax.swing.JLabel lblFirmarRutaLlavePrivada;
    private javax.swing.JLabel lblRutaArchivo;
    private javax.swing.JLabel lblVerificarRutaPublica;
    // End of variables declaration//GEN-END:variables
}
